twitter_key:  cBYNfhFiToHfVir6TaegSseHe
twitter_secret: B2ttJAgIUIVYpQCVmg898y7PqFVCvAxukMaQ2ea86gOJbuFafR
twitter_token: 24500472-khTZxEUlMJ0ySEGwu9kSnE6TwpO9erddpd50ZXk0O
twitter_token_ssecret: iXQLu00wu9YJyw7tm94ya6cm6PJsrBjZcxUyB1dfofoMu

yelp_key: JPjXiphCtMc9aqN4n8Svhg
yelp_secret: _XUr_r49IRDHAfabdZQ8unvbHOk
yelp_token: -IX46wDpO8-28z1Qtk5pLpH3zHYk25Ki
yelp_token_secret: gzDAP_5vWlIPVFoMsyRit6Rfe5g
yelp_access: HnFxmv9lpPxBUwRG114IR6zsWr4C3QMkByLwSwb8oDL-glaJy7bIBHE27zOx7Aphi0pydWea3z3ZI_uJhzmT79HZbAnxQRyagkP0lUwizhRiOnRkuXNq6ijGY-hXWHYx

news: d7bd4c29053c495c9845714ee487f096
walmart: 47adsm6u2vf5ea8geznqm9qv
