development:
  adapter: postgresql
  encoding: utf8
  database: retrospeck_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: retrospeck_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: retrospeck_production
  pool: 5
  username:
  password:

cucumber:
  <<: *TEST
